spring:
  application:
    name: lzhphantom-user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    timeout: 86400
server:
  port: 8012
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    version: v4.0
    group:
      test1:
        api-rule: package
        api-rule-resources:
          - com.lzhphantom.lzhphantom_findfriendsbackend.controller